### ISSUE TITLE
/data modify commands throwing an error

### ISSUE THREAD

**Issue by TheMrZZ** [Levertion/mcfunction-langserver#133]
`/data` commands are throwing an error at the NBT Path. It doesn't understand that the whitespace means the NBT Path is over:
![Capture d’écran (50)](https://user-images.githubusercontent.com/30944236/55634671-3f119e00-57bf-11e9-9718-24f9cb41a5ce.png)

The given error is: `Bad character ' ' mcfunction(argument.nbt_path.badchar)`
![Capture d’écran (52)](https://user-images.githubusercontent.com/30944236/55634879-ae878d80-57bf-11e9-9630-f7c7777e9537.png)
![Capture d’écran (53)](https://user-images.githubusercontent.com/30944236/55634883-b0515100-57bf-11e9-9a3f-87f90ab86915.png)

**Comment by Levertion** [comment]
Thanks for the report! I'm doing a large refactoring into https://github.com/levertion/mcfunction, so I'm not going to debug this now, but I'll make sure this gets fixed.

I think I did just forget to allow whitespace to end the path...
